# Generated by Django 4.1.7 on 2023-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_social_icon', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='coverimage',
            field=models.ImageField(blank=True, default='cover/default.jpg', null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='dp/default.png', null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='add_on',
            field=models.ManyToManyField(blank=True, to='user.extrafield'),
        ),
    ]
