# Generated by Django 4.1.7 on 2023-03-15 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_extrafield_alter_profile_coverimage_alter_profile_dp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add_on',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
