# Generated by Django 4.1.7 on 2023-03-15 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_remove_profile_add_on_extrafield_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafield',
            name='user',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
