# Generated by Django 4.1.7 on 2023-03-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_extrafield_user_extrafield_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraField',
        ),
    ]
