# Generated by Django 4.1.7 on 2023-03-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_phonenumber_user_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp',
        ),
    ]
