# Generated by Django 4.1.7 on 2023-03-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
