# Generated by Django 4.1.7 on 2023-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_profile_vedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg',
            field=models.CharField(blank=True, default='white', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(blank=True, default='black', max_length=250, null=True),
        ),
    ]
