# Generated by Django 4.1.7 on 2023-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_profile_bg_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_gradient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_status',
            field=models.BooleanField(default=True),
        ),
    ]
