# Generated by Django 4.1.7 on 2023-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_profile_bg_gradient_profile_qr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_gradient',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
