# Generated by Django 4.1.7 on 2023-04-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='icon_html',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
