# Generated by Django 4.1.7 on 2023-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_extrafield_icon_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafield',
            name='icon',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='icon',
            field=models.ManyToManyField(blank=True, null=True, to='user.icon'),
        ),
    ]
