# Generated by Django 4.1.7 on 2023-04-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_extrafield_icon_extrafield_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafield',
            name='icons',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='icons',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
