# Generated by Django 4.1.7 on 2023-04-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_extrafield_icons_extrafield_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='icons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
