# Generated by Django 4.1.7 on 2023-04-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_extrafield_icon_extrafield_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='icon',
            field=models.ManyToManyField(to='user.icon'),
        ),
    ]
