# Generated by Django 4.1.7 on 2023-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_extrafield_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='icon',
            field=models.ManyToManyField(null=True, to='user.icon'),
        ),
    ]
