# Generated by Django 4.1.7 on 2023-04-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_card_profile_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
