# Generated by Django 4.1.7 on 2023-04-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_carddesign_alter_profile_card_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
